### ISSUE TITLE
fix: missing the  directSource 

### ISSUE THREAD

**Issue by idan003** [pauli2406/xtream_code_client#15]
hello,

when im fetching the live stream or also vod the directSource is missing the url for the video player

`
Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text("$type Items")),
        body: FutureBuilder<List<dynamic>>(
          future: fetchItems(),
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.done &&
                snapshot.hasData) {
              return ListView.builder(
                itemCount: snapshot.data!.length,
                itemBuilder: (_, index) => ListTile(
                  leading: const Icon(Icons.tv),
                  title: Text(snapshot.data![index].name),
                  onTap: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => VideoPlayerScreen(
                            channel: snapshot.data![index].directSource),
                      ),
                    );
                  },
                ),
              );
            }
            return snapshot.hasError
                ? Text('Error: ${snapshot.error}')
                : const CircularProgressIndicator();
          },
        ),
      );
`
      
` 
VideoPlayerScreen(channel: snapshot.data![index].directSource)
 `
                            
  can you tell me if there is another paramer to fetch the source url?

**Comment by pauli2406** [comment]
The client provided helper methods for this, as an example for a vod


```dart

final vodItems = await client.vodItems()[0];
client.movieUrl(
  vod.streamId!, 
  vod.containerExtension!),
)
```

**Comment by idan003** [comment]
its also for live tv?

**Comment by pauli2406** [comment]
> its also for live tv?

Well, there is another helper for that :)

**Comment by idan003** [comment]
can you tell me with list i need to provide on the streamUrl parameter?

**Comment by pauli2406** [comment]
you need to provide the formats your provider supports, like ".ts", ".m3u8" etc

use client.serverInformation() before, than you will find the supported types in the object within userInfo

**Comment by idan003** [comment]
thank you for all the help :)
