### ISSUE TITLE
fix: Undefined class 'XtreamCodeClient'.

### ISSUE THREAD

**Issue by bennajah** [pauli2406/xtream_code_client#6]
**Undefined class 'XtreamCodeClient'.**

![image](https://github.com/pauli2406/xtream_code_client/assets/38137719/7772544e-0a32-4372-97ad-e9e4bbbc0bbe)

**Comment by pauli2406** [comment]
Fixed in https://github.com/pauli2406/xtream_code_client/pull/11
Class is now exported
