### ISSUE TITLE
fix: Cast Error

### ISSUE THREAD

**Issue by mikailkse** [pauli2406/xtream_code_client#8]
try {
      await XtreamCode.initialize(
        url: url ?? "",
        port: port ?? "",
        username: username ?? "",
        password: password ?? "",
      );
      final client = XtreamCode.instance.client;

      var serverInfo = await client.serverInformation();

      var seriesCategories = await client.seriesCategories();
      var seriesItems =
          await client.seriesItems(category: seriesCategories.first);
      var seriesInfo = await client.seriesInfo(seriesItems.first);
      // await navigateToHomeView(context);
    } catch (e) {
      print(e);
    } finally {
      setLoading(false);
    }

Firstly, I can access categories but when I come to the 2nd step, namely seriesItems and seriesInfo, I cannot access other models I get a cast error "type 'String' is not a subtype of type 'num?' in type cast"

**Comment by pauli2406** [comment]
Should be fixed by https://github.com/pauli2406/xtream_code_client/pull/10
